// Reads the face-api.js TinyFaceDetector model files from public/models/
// and writes them as a single JS module with base64-encoded weights.
// This bundles the model into the JS at build time so no network
// requests are needed at runtime — bypassing ngrok interstitials entirely.

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const modelsDir = resolve(__dirname, '../public/models');

const shard    = readFileSync(resolve(modelsDir, 'tiny_face_detector_model-shard1'));
const manifest = JSON.parse(readFileSync(resolve(modelsDir, 'tiny_face_detector_model-weights_manifest.json'), 'utf8'));

const out = `// AUTO-GENERATED by scripts/generateModel.mjs — do not edit by hand
export const shardBase64 = "${shard.toString('base64')}";
export const modelManifest = ${JSON.stringify(manifest)};
`;

const outPath = resolve(__dirname, '../src/tinyFaceDetectorModel.js');
writeFileSync(outPath, out);
console.log(`Generated tinyFaceDetectorModel.js  (shard: ${shard.length} bytes → ${Math.round(out.length / 1024)} KB module)`);
